#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


# node.js
add-apt-repository -y ppa:chris-lea/node.js

# let 'er rip
apt-get -y update

# ♬ ♬ ♬ bear neccessities ♬ ♬ ♬
apt-get install -y software-properties-common
apt-get install -y python-software-properties
apt-get install -y btrfs-tools
apt-get install -y git
apt-get install -y curl
apt-get install -y apt-transport-http
apt-get install -y ssh
apt-get install -y python
apt-get install -y g++
apt-get install -y make
apt-get install -y pkg-config
apt-get install -y man
apt-get install -y python-pip
apt-get install -y python-dev
apt-get install -y jq
apt-get install -y libfuse-dev



# clean up
apt-get -y autoremove
apt-get -y autoclean
apt-get -y clean

# add the jam job
cp /logjam/demo/jam_job.conf /etc/init/jam_job.conf

# install logjam
# cd /logjam && npm install -g
# jam --help
